<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LdcUserProfile\Module'                        => __DIR__ . '/Module.php',
    'LdcUserProfile\Controller\ProfileController' => __DIR__ . '/src/LdcUserProfile/Controller/ProfileController.php',
);