<h1><?php echo $this->translate('Your Profile'); ?></h1>

<?php
if (!$this->options->isEnabled()) {
    echo $this->translate('Profile page is disabled');
    return;
}
$form = $this->profileForm;
$form->prepare();
$form->setAttribute('action', $this->url('ldc-user-profile'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
    <?php foreach ($form->getFieldsets() as $fieldset): ?>
        <?php echo $this->render('ldc-user-profile/profile/extension/' . $fieldset->getName(), array('fieldset' => $fieldset)); ?>
    <?php endforeach ?>

    <?php foreach ($form->getElements() as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button && !$element instanceof Zend\Form\Element\Hidden): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach;?>

    </dl>
<?php echo $this->form()->closeTag() ?>